export const homeURL = "/"
export const registerURL = "/register"
export const loginURL = "/login"
export const profileURL = "/profile"
export const reserveURL = "/reserve/:movieId"
export const adminURL = "/admin"
export const movieURL = "/movie"